In [23]:
import os
import warnings
import tensorflow as tf
warnings.filterwarnings("ignore")
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

In [35]:
daily_sales_number = [21, 22, -109, -1, 32, 34, 31]

In [36]:
tf_data = tf.data.Dataset.from_tensor_slices(daily_sales_number)

In [37]:
tf_data

<TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [40]:
next(iter(tf_data)).numpy()

21

In [6]:
for s in tf_data:
    print(s)

tf.Tensor(21, shape=(), dtype=int32)
tf.Tensor(22, shape=(), dtype=int32)
tf.Tensor(-109, shape=(), dtype=int32)
tf.Tensor(-1, shape=(), dtype=int32)
tf.Tensor(32, shape=(), dtype=int32)
tf.Tensor(34, shape=(), dtype=int32)
tf.Tensor(31, shape=(), dtype=int32)


In [7]:
for s in tf_data:
    print(s.numpy())

21
22
-109
-1
32
34
31


In [8]:
for s in tf_data.as_numpy_iterator():
    print(s)

21
22
-109
-1
32
34
31


In [9]:
for s in tf_data.take(3):
    print(s.numpy())

21
22
-109


# Filter

In [10]:
tf_filtered_data = tf_data.filter(lambda x: x>0)

Instructions for updating:
Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089


In [11]:
for s in tf_filtered_data:
    print(s.numpy())

21
22
32
34
31


# Transformation

#### Map function will take the individual elements and apply the transformations

In [12]:
tf_transformed_data = tf_filtered_data.map(lambda x: x*72)

In [13]:
for s in tf_transformed_data:
    print(s.numpy())

1512
1584
2304
2448
2232


In [16]:
# You can specify the buffer size here which is basically a way to randomize the data by creating buffer batches and filling the buffer after taking a random element
for s in tf_transformed_data.shuffle(3):
    print(s.numpy())

2304
2448
1584
2232
1512


In [19]:
for s in tf_transformed_data.batch(2):
    print(s.numpy())

[1512 1584]
[2304 2448]
[2232]


# Doing everything at once

In [25]:
tf_final = tf_data.filter(lambda x: x>20).map(lambda y: y*70).shuffle(2).batch(2)

In [26]:
for s in tf_final:
    print(s)

tf.Tensor([1540 1470], shape=(2,), dtype=int32)
tf.Tensor([2240 2170], shape=(2,), dtype=int32)
tf.Tensor([2380], shape=(1,), dtype=int32)
