In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [3]:
prob = 0.5
dropout = nn.Dropout(p=prob)

In [4]:
x = torch.ones(10)
dropout.train()
y = dropout(x)
print(x)
# pytorch scales up the weight in training (w*1/(1-p))
# that is why you see 2, the 0s indicated the units are dropped out
print(y)
torch.mean(y)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0., 2., 2., 2., 2.])


tensor(0.8000)

In [5]:
# dropout is turned off in eval mode
dropout.eval()
y = dropout(x)
print(x)
print(y)
print(torch.mean(y))


tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [6]:
# annoyingly F.dropout() is not deactivated in eval mode
dropout.eval()
y = F.dropout(x)
print(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([2., 2., 0., 0., 0., 2., 2., 2., 2., 0.])
tensor(1.2000)


In [7]:
# manually turning it off
dropout.eval()
y = F.dropout(x, training=False)
print(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [23]:
# the model needs to be reset after toggling into eval mode